// Generated by vite-plugin-pocketbase

import PocketBase, { RecordService, BaseModel } from 'pocketbase';

declare global {
  type Id = string
  type Uri = string
  type GeoPoint = { lat: number; lon: number };
  
  // users
  interface User extends BaseModel {
    id: string;
    email: string;
    emailVisibility?: boolean;
    verified?: boolean;
    firstName?: string;
    lastName?: string;
    avatar?: string;
    created?: string;
    updated?: string;
  }

  // links
  interface Link extends BaseModel {
    id: string;
    label?: string;
    url?: string;
    cover?: string;
    category?: Id;
    created?: string;
    updated?: string;
  }

  // books
  interface Book extends BaseModel {
    id: string;
    title: string;
    field?: string;
    author?: string;
    studio?: Id;
    cover?: string;
    pubYear?: number;
    bookLink?: string;
    publisher?: Id;
    visible: boolean;
    created?: string;
    updated?: string;
  }

  // studios
  interface Studio extends BaseModel {
    id: string;
    name?: string;
    field?: string;
    location?: geoPoint;
    internships?: boolean;
    url?: string;
    created?: string;
    updated?: string;
  }

  // publishers
  interface Publisher extends BaseModel {
    id: string;
    name?: string;
    created?: string;
    updated?: string;
  }

  // resources
  interface Resource extends BaseModel {
    id: string;
    title?: string;
    subtitle?: string;
    cover?: string;
    layout?: string;
    attribution?: string;
    attributionLink?: string;
    classes?: string;
    slug?: string;
    category?: Id;
    created?: string;
    updated?: string;
  }

  // link_categories
  interface LinkCategory extends BaseModel {
    id: string;
    label?: string;
    cover?: string;
    standalone: boolean;
    created?: string;
    updated?: string;
  }

  // events
  interface Event extends BaseModel {
    id: string;
    name?: string;
    datetime?: string;
    description?: string;
    allDay: boolean;
    created?: string;
    updated?: string;
  }

  // members
  interface Member extends BaseModel {
    id: string;
    member?: Id;
    name?: string;
    role?: string;
    profile?: string;
    avatar?: string;
    created?: string;
    updated?: string;
  }

  // submissions
  interface Submission extends BaseModel {
    id: string;
    name?: string;
    email?: string;
    submission?: string;
    created?: string;
    updated?: string;
  }

  interface TypedPocketBase extends PocketBase {
    collection(idOrName: "users"): RecordService<User>;
    collection(idOrName: "links"): RecordService<Link>;
    collection(idOrName: "books"): RecordService<Book>;
    collection(idOrName: "studios"): RecordService<Studio>;
    collection(idOrName: "publishers"): RecordService<Publisher>;
    collection(idOrName: "resources"): RecordService<Resource>;
    collection(idOrName: "link_categories"): RecordService<LinkCategory>;
    collection(idOrName: "events"): RecordService<Event>;
    collection(idOrName: "members"): RecordService<Member>;
    collection(idOrName: "submissions"): RecordService<Submission>;
  }
}
export {}