// Generated by vite-plugin-pocketbase

export * from "Pocketbase";
export type Id = string;

import type { BaseModel } from "Pocketbase";

// users
export interface User extends BaseModel {
  id: string;
  email: string;
  emailVisibility?: boolean;
  verified?: boolean;
  firstName?: string;
  lastName?: string;
  avatar?: string;
  created?: string;
  updated?: string;
}

// links
export interface Link extends BaseModel {
  id: string;
  label?: string;
  url?: string;
  cover?: string;
  category?: Id;
  created?: string;
  updated?: string;
}

// books
export interface Book extends BaseModel {
  id: string;
  title: string;
  field?: string;
  author?: string;
  studio?: Id;
  cover?: string;
  pubYear?: number;
  bookLink?: string;
  publisher?: Id;
  visible: boolean;
  created?: string;
  updated?: string;
}

// studios
export interface Studio extends BaseModel {
  id: string;
  name?: string;
  field?: string;
  location?: geoPoint;
  internships?: boolean;
  url?: string;
  created?: string;
  updated?: string;
}

// publishers
export interface Publisher extends BaseModel {
  id: string;
  name?: string;
  created?: string;
  updated?: string;
}

// resources
export interface Resource extends BaseModel {
  id: string;
  title?: string;
  subtitle?: string;
  cover?: string;
  layout?: string;
  attribution?: string;
  classes?: string;
  slug?: string;
  category?: Id;
  created?: string;
  updated?: string;
}

// link_categories
export interface LinkCategory extends BaseModel {
  id: string;
  label?: string;
  cover?: string;
  standalone: boolean;
  created?: string;
  updated?: string;
}

// events
export interface Event extends BaseModel {
  id: string;
  name?: string;
  datetime?: string;
  description?: editor;
  allDay: boolean;
  created?: string;
  updated?: string;
}

// members
export interface Member extends BaseModel {
  id: string;
  member?: Id;
  name?: string;
  role?: string;
  profile?: string;
  avatar?: string;
  created?: string;
  updated?: string;
}