// Generated by vite-plugin-pocketbase

export * from "Pocketbase";
export type Id = string;

import type { BaseModel } from "Pocketbase";

// users
export interface UserModel extends BaseModel {
  id: string;
  email: string;
  emailVisibility?: boolean;
  verified?: boolean;
  firstName?: string;
  lastName?: string;
  avatar?: string;
  created?: string;
  updated?: string;
}

// links
export interface LinkModel extends BaseModel {
  id: string;
  label?: string;
  url?: string;
  cover?: string;
  category?: Id;
  created?: string;
  updated?: string;
}

// books
export interface BookModel extends BaseModel {
  id: string;
  title: string;
  field?: string;
  author?: string;
  studio?: Id;
  cover?: string;
  pubYear?: number;
  bookLink?: string;
  publisher?: Id;
  visible: boolean;
  created?: string;
  updated?: string;
}

// studios
export interface StudioModel extends BaseModel {
  id: string;
  name?: string;
  field?: string;
  location?: geoPoint;
  internships?: boolean;
  url?: string;
  created?: string;
  updated?: string;
}

// publishers
export interface PublisherModel extends BaseModel {
  id: string;
  name?: string;
  created?: string;
  updated?: string;
}

// resources
export interface ResourceModel extends BaseModel {
  id: string;
  title?: string;
  subtitle?: string;
  cover?: string;
  layout?: string;
  attribution?: string;
  classes?: string;
  slug?: string;
  category?: Id;
  created?: string;
  updated?: string;
}

// link_categories
export interface LinkCategoryModel extends BaseModel {
  id: string;
  label?: string;
  cover?: string;
  standalone: boolean;
  created?: string;
  updated?: string;
}