import { CodeWriter } from "../codewriter";
import type { PluginOptions } from "./types";
import { type CollectionField, type CollectionModel } from "pocketbase";


const getFieldType = (field: any) => {
  switch (field.type) {
    case "text":
    case "email":
    case "url":
    case "select":
    case "file":
    case "autodate":
      return "string";
    case "relation":
      return "Id";
    case "number":
      return "number";
    case "bool":
      return "boolean";
    case "date":
      return "string"; // or Date, depending on your preference
    case "json":
      return "any"; // or a more specific type if you know the structure
    default:
      return field.type; // fallback to the field type if it's custom
  }
};


const generateType = (
  options: PluginOptions,
  collection: CollectionModel
) => {
  var w = new CodeWriter();

  w.writeLine("// " + collection.name);
  w.writeOpenBracket(`export interface ${options.collectionNameResolver(collection)}${options.nameSuffix}${options.useBaseModel ? ' extends BaseModel' : '' }`    );

  w.writeLines(collection.fields.filter(f => options.fieldFilter(f, options)), (field: CollectionField) => {
    const fieldType = getFieldType(field);
    const optionalFlag = field.required ? "" : "?";
    return `${options.fieldNameResolver(field)}${optionalFlag}: ${fieldType};`;
  });

  w.writeCloseBracket();

  return w.toString();
};

export function generateDTS(options: PluginOptions,collections: CollectionModel[]) {

  const w = new CodeWriter();
  w.writeLine(`// Generated by vite-plugin-pocketbase`);
  w.writeBlankLine();
  w.writeLine(`export * from "Pocketbase";`);
  w.writeLine(`export type Id = string;`);
  w.writeBlankLine();
  w.writeLine('import type { BaseModel } from "Pocketbase";');
  w.writeBlankLine();

  w.each(collections.filter( c => options.collectionFilter(c, options)), (coll:CollectionModel) => {
    w.writeLine(generateType(options, coll));
  });

  return w.toString().trim();

}
